#.github/workflows/lint.yml
name: "PR Lint Check"
on:
  pull_request: # PR 이벤트 발생 시
    branches: # 타겟 브랜치가 다음과 같을 때
      - feat   # 'feat' 브랜치일 경우에만 이 워크플로를 실행
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # 코드 가져오기 (v4 권장)

      - name: Setup Node.js
        uses: actions/setup-node@v3 # Node.js 설정 (v4 권장)
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci # 의존성 설치 (package-lock.json 기반)

      - name: Run ESLint
        run: npm run lint # package.json 내의 lint 스크립트 실행
