name: "PR Lint Check"
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 레포 루트에서 실행하도록 working-directory를 안 쓰거나 "./"로 지정
      - name: Install dependencies
        run: npm ci
        # working-directory: .   # (→ 이 줄을 아예 지워도 됩니다)

      - name: Run ESLint
        run: npm run lint
        # working-directory: .
